// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"roofix/ent/apiuser"
	"roofix/ent/estimate"
	"roofix/ent/estimateactivity"
	"roofix/ent/predicate"
	"roofix/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EstimateActivityQuery is the builder for querying EstimateActivity entities.
type EstimateActivityQuery struct {
	config
	ctx            *QueryContext
	order          []estimateactivity.OrderOption
	inters         []Interceptor
	predicates     []predicate.EstimateActivity
	withEstimate   *EstimateQuery
	withCreator    *UserQuery
	withCreatorAPI *ApiUserQuery
	withFKs        bool
	loadTotal      []func(context.Context, []*EstimateActivity) error
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EstimateActivityQuery builder.
func (eaq *EstimateActivityQuery) Where(ps ...predicate.EstimateActivity) *EstimateActivityQuery {
	eaq.predicates = append(eaq.predicates, ps...)
	return eaq
}

// Limit the number of records to be returned by this query.
func (eaq *EstimateActivityQuery) Limit(limit int) *EstimateActivityQuery {
	eaq.ctx.Limit = &limit
	return eaq
}

// Offset to start from.
func (eaq *EstimateActivityQuery) Offset(offset int) *EstimateActivityQuery {
	eaq.ctx.Offset = &offset
	return eaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eaq *EstimateActivityQuery) Unique(unique bool) *EstimateActivityQuery {
	eaq.ctx.Unique = &unique
	return eaq
}

// Order specifies how the records should be ordered.
func (eaq *EstimateActivityQuery) Order(o ...estimateactivity.OrderOption) *EstimateActivityQuery {
	eaq.order = append(eaq.order, o...)
	return eaq
}

// QueryEstimate chains the current query on the "estimate" edge.
func (eaq *EstimateActivityQuery) QueryEstimate() *EstimateQuery {
	query := (&EstimateClient{config: eaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(estimateactivity.Table, estimateactivity.FieldID, selector),
			sqlgraph.To(estimate.Table, estimate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, estimateactivity.EstimateTable, estimateactivity.EstimateColumn),
		)
		fromU = sqlgraph.SetNeighbors(eaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreator chains the current query on the "creator" edge.
func (eaq *EstimateActivityQuery) QueryCreator() *UserQuery {
	query := (&UserClient{config: eaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(estimateactivity.Table, estimateactivity.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, estimateactivity.CreatorTable, estimateactivity.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(eaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreatorAPI chains the current query on the "creator_api" edge.
func (eaq *EstimateActivityQuery) QueryCreatorAPI() *ApiUserQuery {
	query := (&ApiUserClient{config: eaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(estimateactivity.Table, estimateactivity.FieldID, selector),
			sqlgraph.To(apiuser.Table, apiuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, estimateactivity.CreatorAPITable, estimateactivity.CreatorAPIColumn),
		)
		fromU = sqlgraph.SetNeighbors(eaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EstimateActivity entity from the query.
// Returns a *NotFoundError when no EstimateActivity was found.
func (eaq *EstimateActivityQuery) First(ctx context.Context) (*EstimateActivity, error) {
	nodes, err := eaq.Limit(1).All(setContextOp(ctx, eaq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{estimateactivity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eaq *EstimateActivityQuery) FirstX(ctx context.Context) *EstimateActivity {
	node, err := eaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EstimateActivity ID from the query.
// Returns a *NotFoundError when no EstimateActivity ID was found.
func (eaq *EstimateActivityQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = eaq.Limit(1).IDs(setContextOp(ctx, eaq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{estimateactivity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eaq *EstimateActivityQuery) FirstIDX(ctx context.Context) string {
	id, err := eaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EstimateActivity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EstimateActivity entity is found.
// Returns a *NotFoundError when no EstimateActivity entities are found.
func (eaq *EstimateActivityQuery) Only(ctx context.Context) (*EstimateActivity, error) {
	nodes, err := eaq.Limit(2).All(setContextOp(ctx, eaq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{estimateactivity.Label}
	default:
		return nil, &NotSingularError{estimateactivity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eaq *EstimateActivityQuery) OnlyX(ctx context.Context) *EstimateActivity {
	node, err := eaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EstimateActivity ID in the query.
// Returns a *NotSingularError when more than one EstimateActivity ID is found.
// Returns a *NotFoundError when no entities are found.
func (eaq *EstimateActivityQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = eaq.Limit(2).IDs(setContextOp(ctx, eaq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{estimateactivity.Label}
	default:
		err = &NotSingularError{estimateactivity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eaq *EstimateActivityQuery) OnlyIDX(ctx context.Context) string {
	id, err := eaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EstimateActivities.
func (eaq *EstimateActivityQuery) All(ctx context.Context) ([]*EstimateActivity, error) {
	ctx = setContextOp(ctx, eaq.ctx, "All")
	if err := eaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EstimateActivity, *EstimateActivityQuery]()
	return withInterceptors[[]*EstimateActivity](ctx, eaq, qr, eaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eaq *EstimateActivityQuery) AllX(ctx context.Context) []*EstimateActivity {
	nodes, err := eaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EstimateActivity IDs.
func (eaq *EstimateActivityQuery) IDs(ctx context.Context) (ids []string, err error) {
	if eaq.ctx.Unique == nil && eaq.path != nil {
		eaq.Unique(true)
	}
	ctx = setContextOp(ctx, eaq.ctx, "IDs")
	if err = eaq.Select(estimateactivity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eaq *EstimateActivityQuery) IDsX(ctx context.Context) []string {
	ids, err := eaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eaq *EstimateActivityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eaq.ctx, "Count")
	if err := eaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eaq, querierCount[*EstimateActivityQuery](), eaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eaq *EstimateActivityQuery) CountX(ctx context.Context) int {
	count, err := eaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eaq *EstimateActivityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eaq.ctx, "Exist")
	switch _, err := eaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eaq *EstimateActivityQuery) ExistX(ctx context.Context) bool {
	exist, err := eaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EstimateActivityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eaq *EstimateActivityQuery) Clone() *EstimateActivityQuery {
	if eaq == nil {
		return nil
	}
	return &EstimateActivityQuery{
		config:         eaq.config,
		ctx:            eaq.ctx.Clone(),
		order:          append([]estimateactivity.OrderOption{}, eaq.order...),
		inters:         append([]Interceptor{}, eaq.inters...),
		predicates:     append([]predicate.EstimateActivity{}, eaq.predicates...),
		withEstimate:   eaq.withEstimate.Clone(),
		withCreator:    eaq.withCreator.Clone(),
		withCreatorAPI: eaq.withCreatorAPI.Clone(),
		// clone intermediate query.
		sql:  eaq.sql.Clone(),
		path: eaq.path,
	}
}

// WithEstimate tells the query-builder to eager-load the nodes that are connected to
// the "estimate" edge. The optional arguments are used to configure the query builder of the edge.
func (eaq *EstimateActivityQuery) WithEstimate(opts ...func(*EstimateQuery)) *EstimateActivityQuery {
	query := (&EstimateClient{config: eaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eaq.withEstimate = query
	return eaq
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (eaq *EstimateActivityQuery) WithCreator(opts ...func(*UserQuery)) *EstimateActivityQuery {
	query := (&UserClient{config: eaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eaq.withCreator = query
	return eaq
}

// WithCreatorAPI tells the query-builder to eager-load the nodes that are connected to
// the "creator_api" edge. The optional arguments are used to configure the query builder of the edge.
func (eaq *EstimateActivityQuery) WithCreatorAPI(opts ...func(*ApiUserQuery)) *EstimateActivityQuery {
	query := (&ApiUserClient{config: eaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eaq.withCreatorAPI = query
	return eaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EstimateActivity.Query().
//		GroupBy(estimateactivity.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eaq *EstimateActivityQuery) GroupBy(field string, fields ...string) *EstimateActivityGroupBy {
	eaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EstimateActivityGroupBy{build: eaq}
	grbuild.flds = &eaq.ctx.Fields
	grbuild.label = estimateactivity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//	}
//
//	client.EstimateActivity.Query().
//		Select(estimateactivity.FieldCreatedAt).
//		Scan(ctx, &v)
func (eaq *EstimateActivityQuery) Select(fields ...string) *EstimateActivitySelect {
	eaq.ctx.Fields = append(eaq.ctx.Fields, fields...)
	sbuild := &EstimateActivitySelect{EstimateActivityQuery: eaq}
	sbuild.label = estimateactivity.Label
	sbuild.flds, sbuild.scan = &eaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EstimateActivitySelect configured with the given aggregations.
func (eaq *EstimateActivityQuery) Aggregate(fns ...AggregateFunc) *EstimateActivitySelect {
	return eaq.Select().Aggregate(fns...)
}

func (eaq *EstimateActivityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eaq); err != nil {
				return err
			}
		}
	}
	for _, f := range eaq.ctx.Fields {
		if !estimateactivity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eaq.path != nil {
		prev, err := eaq.path(ctx)
		if err != nil {
			return err
		}
		eaq.sql = prev
	}
	return nil
}

func (eaq *EstimateActivityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EstimateActivity, error) {
	var (
		nodes       = []*EstimateActivity{}
		withFKs     = eaq.withFKs
		_spec       = eaq.querySpec()
		loadedTypes = [3]bool{
			eaq.withEstimate != nil,
			eaq.withCreator != nil,
			eaq.withCreatorAPI != nil,
		}
	)
	if eaq.withEstimate != nil || eaq.withCreator != nil || eaq.withCreatorAPI != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, estimateactivity.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EstimateActivity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EstimateActivity{config: eaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(eaq.modifiers) > 0 {
		_spec.Modifiers = eaq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eaq.withEstimate; query != nil {
		if err := eaq.loadEstimate(ctx, query, nodes, nil,
			func(n *EstimateActivity, e *Estimate) { n.Edges.Estimate = e }); err != nil {
			return nil, err
		}
	}
	if query := eaq.withCreator; query != nil {
		if err := eaq.loadCreator(ctx, query, nodes, nil,
			func(n *EstimateActivity, e *User) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	if query := eaq.withCreatorAPI; query != nil {
		if err := eaq.loadCreatorAPI(ctx, query, nodes, nil,
			func(n *EstimateActivity, e *ApiUser) { n.Edges.CreatorAPI = e }); err != nil {
			return nil, err
		}
	}
	for i := range eaq.loadTotal {
		if err := eaq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eaq *EstimateActivityQuery) loadEstimate(ctx context.Context, query *EstimateQuery, nodes []*EstimateActivity, init func(*EstimateActivity), assign func(*EstimateActivity, *Estimate)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*EstimateActivity)
	for i := range nodes {
		if nodes[i].estimate_id == nil {
			continue
		}
		fk := *nodes[i].estimate_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(estimate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "estimate_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (eaq *EstimateActivityQuery) loadCreator(ctx context.Context, query *UserQuery, nodes []*EstimateActivity, init func(*EstimateActivity), assign func(*EstimateActivity, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*EstimateActivity)
	for i := range nodes {
		if nodes[i].creator_id == nil {
			continue
		}
		fk := *nodes[i].creator_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "creator_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (eaq *EstimateActivityQuery) loadCreatorAPI(ctx context.Context, query *ApiUserQuery, nodes []*EstimateActivity, init func(*EstimateActivity), assign func(*EstimateActivity, *ApiUser)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*EstimateActivity)
	for i := range nodes {
		if nodes[i].api_user_id == nil {
			continue
		}
		fk := *nodes[i].api_user_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apiuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "api_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (eaq *EstimateActivityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eaq.querySpec()
	if len(eaq.modifiers) > 0 {
		_spec.Modifiers = eaq.modifiers
	}
	_spec.Node.Columns = eaq.ctx.Fields
	if len(eaq.ctx.Fields) > 0 {
		_spec.Unique = eaq.ctx.Unique != nil && *eaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eaq.driver, _spec)
}

func (eaq *EstimateActivityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(estimateactivity.Table, estimateactivity.Columns, sqlgraph.NewFieldSpec(estimateactivity.FieldID, field.TypeString))
	_spec.From = eaq.sql
	if unique := eaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eaq.path != nil {
		_spec.Unique = true
	}
	if fields := eaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, estimateactivity.FieldID)
		for i := range fields {
			if fields[i] != estimateactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eaq *EstimateActivityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eaq.driver.Dialect())
	t1 := builder.Table(estimateactivity.Table)
	columns := eaq.ctx.Fields
	if len(columns) == 0 {
		columns = estimateactivity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eaq.sql != nil {
		selector = eaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eaq.ctx.Unique != nil && *eaq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range eaq.modifiers {
		m(selector)
	}
	for _, p := range eaq.predicates {
		p(selector)
	}
	for _, p := range eaq.order {
		p(selector)
	}
	if offset := eaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (eaq *EstimateActivityQuery) Modify(modifiers ...func(s *sql.Selector)) *EstimateActivitySelect {
	eaq.modifiers = append(eaq.modifiers, modifiers...)
	return eaq.Select()
}

// EstimateActivityGroupBy is the group-by builder for EstimateActivity entities.
type EstimateActivityGroupBy struct {
	selector
	build *EstimateActivityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eagb *EstimateActivityGroupBy) Aggregate(fns ...AggregateFunc) *EstimateActivityGroupBy {
	eagb.fns = append(eagb.fns, fns...)
	return eagb
}

// Scan applies the selector query and scans the result into the given value.
func (eagb *EstimateActivityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eagb.build.ctx, "GroupBy")
	if err := eagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EstimateActivityQuery, *EstimateActivityGroupBy](ctx, eagb.build, eagb, eagb.build.inters, v)
}

func (eagb *EstimateActivityGroupBy) sqlScan(ctx context.Context, root *EstimateActivityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eagb.fns))
	for _, fn := range eagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eagb.flds)+len(eagb.fns))
		for _, f := range *eagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EstimateActivitySelect is the builder for selecting fields of EstimateActivity entities.
type EstimateActivitySelect struct {
	*EstimateActivityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eas *EstimateActivitySelect) Aggregate(fns ...AggregateFunc) *EstimateActivitySelect {
	eas.fns = append(eas.fns, fns...)
	return eas
}

// Scan applies the selector query and scans the result into the given value.
func (eas *EstimateActivitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eas.ctx, "Select")
	if err := eas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EstimateActivityQuery, *EstimateActivitySelect](ctx, eas.EstimateActivityQuery, eas, eas.inters, v)
}

func (eas *EstimateActivitySelect) sqlScan(ctx context.Context, root *EstimateActivityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eas.fns))
	for _, fn := range eas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (eas *EstimateActivitySelect) Modify(modifiers ...func(s *sql.Selector)) *EstimateActivitySelect {
	eas.modifiers = append(eas.modifiers, modifiers...)
	return eas
}
