// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"roofix/ent/job"
	"roofix/ent/jobdocurl"
	"roofix/ent/user"
	"roofix/pkg/enum"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// JobDocURL is the model entity for the JobDocURL schema.
type JobDocURL struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"createdAt"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updatedAt"`
	// Type holds the value of the "type" field.
	Type enum.JobDocUrlType `json:"type,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JobDocURLQuery when eager-loading is set.
	Edges        JobDocURLEdges `json:"edges"`
	job_id       *string
	creator_id   *string
	selectValues sql.SelectValues
}

// JobDocURLEdges holds the relations/edges for other nodes in the graph.
type JobDocURLEdges struct {
	// Job holds the value of the job edge.
	Job *Job `json:"job,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// JobOrErr returns the Job value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JobDocURLEdges) JobOrErr() (*Job, error) {
	if e.loadedTypes[0] {
		if e.Job == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: job.Label}
		}
		return e.Job, nil
	}
	return nil, &NotLoadedError{edge: "job"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JobDocURLEdges) CreatorOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.Creator == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Creator, nil
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobDocURL) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobdocurl.FieldID, jobdocurl.FieldType, jobdocurl.FieldURL:
			values[i] = new(sql.NullString)
		case jobdocurl.FieldCreatedAt, jobdocurl.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case jobdocurl.ForeignKeys[0]: // job_id
			values[i] = new(sql.NullString)
		case jobdocurl.ForeignKeys[1]: // creator_id
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobDocURL fields.
func (jdu *JobDocURL) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobdocurl.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				jdu.ID = value.String
			}
		case jobdocurl.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				jdu.CreatedAt = value.Time
			}
		case jobdocurl.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				jdu.UpdatedAt = value.Time
			}
		case jobdocurl.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				jdu.Type = enum.JobDocUrlType(value.String)
			}
		case jobdocurl.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				jdu.URL = value.String
			}
		case jobdocurl.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				jdu.job_id = new(string)
				*jdu.job_id = value.String
			}
		case jobdocurl.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value.Valid {
				jdu.creator_id = new(string)
				*jdu.creator_id = value.String
			}
		default:
			jdu.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobDocURL.
// This includes values selected through modifiers, order, etc.
func (jdu *JobDocURL) Value(name string) (ent.Value, error) {
	return jdu.selectValues.Get(name)
}

// QueryJob queries the "job" edge of the JobDocURL entity.
func (jdu *JobDocURL) QueryJob() *JobQuery {
	return NewJobDocURLClient(jdu.config).QueryJob(jdu)
}

// QueryCreator queries the "creator" edge of the JobDocURL entity.
func (jdu *JobDocURL) QueryCreator() *UserQuery {
	return NewJobDocURLClient(jdu.config).QueryCreator(jdu)
}

// Update returns a builder for updating this JobDocURL.
// Note that you need to call JobDocURL.Unwrap() before calling this method if this JobDocURL
// was returned from a transaction, and the transaction was committed or rolled back.
func (jdu *JobDocURL) Update() *JobDocURLUpdateOne {
	return NewJobDocURLClient(jdu.config).UpdateOne(jdu)
}

// Unwrap unwraps the JobDocURL entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (jdu *JobDocURL) Unwrap() *JobDocURL {
	_tx, ok := jdu.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobDocURL is not a transactional entity")
	}
	jdu.config.driver = _tx.drv
	return jdu
}

// String implements the fmt.Stringer.
func (jdu *JobDocURL) String() string {
	var builder strings.Builder
	builder.WriteString("JobDocURL(")
	builder.WriteString(fmt.Sprintf("id=%v, ", jdu.ID))
	builder.WriteString("created_at=")
	builder.WriteString(jdu.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(jdu.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", jdu.Type))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(jdu.URL)
	builder.WriteByte(')')
	return builder.String()
}

// JobDocURLs is a parsable slice of JobDocURL.
type JobDocURLs []*JobDocURL
