// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"roofix/ent/partner"
	"roofix/ent/partnerservice"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PartnerService is the model entity for the PartnerService schema.
type PartnerService struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"createdAt"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updatedAt"`
	// ServiceID holds the value of the "service_id" field.
	ServiceID uint8 `json:"service_id,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PartnerServiceQuery when eager-loading is set.
	Edges        PartnerServiceEdges `json:"edges"`
	partner_id   *string
	selectValues sql.SelectValues
}

// PartnerServiceEdges holds the relations/edges for other nodes in the graph.
type PartnerServiceEdges struct {
	// Partner holds the value of the partner edge.
	Partner *Partner `json:"partner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// PartnerOrErr returns the Partner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PartnerServiceEdges) PartnerOrErr() (*Partner, error) {
	if e.loadedTypes[0] {
		if e.Partner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: partner.Label}
		}
		return e.Partner, nil
	}
	return nil, &NotLoadedError{edge: "partner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PartnerService) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case partnerservice.FieldActive:
			values[i] = new(sql.NullBool)
		case partnerservice.FieldServiceID:
			values[i] = new(sql.NullInt64)
		case partnerservice.FieldID:
			values[i] = new(sql.NullString)
		case partnerservice.FieldCreatedAt, partnerservice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case partnerservice.ForeignKeys[0]: // partner_id
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PartnerService fields.
func (ps *PartnerService) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case partnerservice.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ps.ID = value.String
			}
		case partnerservice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ps.CreatedAt = value.Time
			}
		case partnerservice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ps.UpdatedAt = value.Time
			}
		case partnerservice.FieldServiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field service_id", values[i])
			} else if value.Valid {
				ps.ServiceID = uint8(value.Int64)
			}
		case partnerservice.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				ps.Active = value.Bool
			}
		case partnerservice.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field partner_id", values[i])
			} else if value.Valid {
				ps.partner_id = new(string)
				*ps.partner_id = value.String
			}
		default:
			ps.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PartnerService.
// This includes values selected through modifiers, order, etc.
func (ps *PartnerService) Value(name string) (ent.Value, error) {
	return ps.selectValues.Get(name)
}

// QueryPartner queries the "partner" edge of the PartnerService entity.
func (ps *PartnerService) QueryPartner() *PartnerQuery {
	return NewPartnerServiceClient(ps.config).QueryPartner(ps)
}

// Update returns a builder for updating this PartnerService.
// Note that you need to call PartnerService.Unwrap() before calling this method if this PartnerService
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *PartnerService) Update() *PartnerServiceUpdateOne {
	return NewPartnerServiceClient(ps.config).UpdateOne(ps)
}

// Unwrap unwraps the PartnerService entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *PartnerService) Unwrap() *PartnerService {
	_tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: PartnerService is not a transactional entity")
	}
	ps.config.driver = _tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *PartnerService) String() string {
	var builder strings.Builder
	builder.WriteString("PartnerService(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ps.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ps.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ps.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("service_id=")
	builder.WriteString(fmt.Sprintf("%v", ps.ServiceID))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", ps.Active))
	builder.WriteByte(')')
	return builder.String()
}

// PartnerServices is a parsable slice of PartnerService.
type PartnerServices []*PartnerService
