// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"roofix/ent/partnerservice"
	"roofix/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartnerServiceDelete is the builder for deleting a PartnerService entity.
type PartnerServiceDelete struct {
	config
	hooks    []Hook
	mutation *PartnerServiceMutation
}

// Where appends a list predicates to the PartnerServiceDelete builder.
func (psd *PartnerServiceDelete) Where(ps ...predicate.PartnerService) *PartnerServiceDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *PartnerServiceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *PartnerServiceDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *PartnerServiceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(partnerservice.Table, sqlgraph.NewFieldSpec(partnerservice.FieldID, field.TypeString))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// PartnerServiceDeleteOne is the builder for deleting a single PartnerService entity.
type PartnerServiceDeleteOne struct {
	psd *PartnerServiceDelete
}

// Where appends a list predicates to the PartnerServiceDelete builder.
func (psdo *PartnerServiceDeleteOne) Where(ps ...predicate.PartnerService) *PartnerServiceDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *PartnerServiceDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{partnerservice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *PartnerServiceDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
