// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"roofix/ent/partnerservicestate"
	"roofix/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartnerServiceStateDelete is the builder for deleting a PartnerServiceState entity.
type PartnerServiceStateDelete struct {
	config
	hooks    []Hook
	mutation *PartnerServiceStateMutation
}

// Where appends a list predicates to the PartnerServiceStateDelete builder.
func (pssd *PartnerServiceStateDelete) Where(ps ...predicate.PartnerServiceState) *PartnerServiceStateDelete {
	pssd.mutation.Where(ps...)
	return pssd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pssd *PartnerServiceStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pssd.sqlExec, pssd.mutation, pssd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pssd *PartnerServiceStateDelete) ExecX(ctx context.Context) int {
	n, err := pssd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pssd *PartnerServiceStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(partnerservicestate.Table, sqlgraph.NewFieldSpec(partnerservicestate.FieldID, field.TypeString))
	if ps := pssd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pssd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pssd.mutation.done = true
	return affected, err
}

// PartnerServiceStateDeleteOne is the builder for deleting a single PartnerServiceState entity.
type PartnerServiceStateDeleteOne struct {
	pssd *PartnerServiceStateDelete
}

// Where appends a list predicates to the PartnerServiceStateDelete builder.
func (pssdo *PartnerServiceStateDeleteOne) Where(ps ...predicate.PartnerServiceState) *PartnerServiceStateDeleteOne {
	pssdo.pssd.mutation.Where(ps...)
	return pssdo
}

// Exec executes the deletion query.
func (pssdo *PartnerServiceStateDeleteOne) Exec(ctx context.Context) error {
	n, err := pssdo.pssd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{partnerservicestate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pssdo *PartnerServiceStateDeleteOne) ExecX(ctx context.Context) {
	if err := pssdo.Exec(ctx); err != nil {
		panic(err)
	}
}
